// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-my-events.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_events_default = defineTool({
  name: "list_my_events",
  title: "List my events",
  description: "List all events organized by the signed-in Accoro user (their own events, public or private).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of events to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("events").select("id, name, description, event_date, event_time, location, event_number, is_public, status, created_at").eq("organizer_id", ctx.getUserId()).order("event_date", { ascending: true, nullsFirst: false }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-public-events.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_public_events_default = defineTool2({
  name: "list_public_events",
  title: "List public events",
  description: "Browse public Accoro events. Returns upcoming events with basic info a buyer can use to decide which one to purchase tickets for.",
  inputSchema: {
    search: z2.string().optional().describe("Optional substring to filter events by name."),
    limit: z2.number().int().min(1).max(50).optional().describe("Maximum number of events to return. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser2(ctx).from("events").select("id, name, description, event_date, event_time, location, event_number").eq("is_public", true).eq("status", "active").order("event_date", { ascending: true, nullsFirst: false }).limit(limit ?? 20);
    if (search && search.trim()) {
      query = query.ilike("name", `%${search.trim()}%`);
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-event.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.23.8";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function randomEventNumber() {
  return "EVT" + Math.random().toString(36).slice(2, 8).toUpperCase();
}
function randomAccessKey() {
  return Math.random().toString(36).slice(2, 10);
}
var create_event_default = defineTool3({
  name: "create_event",
  title: "Create event",
  description: "Create a new Accoro event owned by the signed-in user. Returns the created event including the auto-generated event number and access key that scanners will use.",
  inputSchema: {
    name: z3.string().describe("Event name shown to buyers."),
    description: z3.string().optional().describe("Long description of the event."),
    event_date: z3.string().optional().describe("Event date in YYYY-MM-DD format."),
    event_time: z3.string().optional().describe("Event time in HH:MM 24h format."),
    location: z3.string().optional().describe("Venue name or full address."),
    is_public: z3.boolean().optional().describe("Whether the event should be listed publicly. Defaults to true.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      organizer_id: ctx.getUserId(),
      name: input.name,
      description: input.description ?? null,
      event_date: input.event_date ?? null,
      event_time: input.event_time ?? null,
      location: input.location ?? null,
      event_number: randomEventNumber(),
      access_key: randomAccessKey(),
      is_public: input.is_public ?? true,
      status: "active"
    };
    const { data, error } = await supabaseForUser3(ctx).from("events").insert(payload).select().single();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.8";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool4({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in Accoro user's profile (name, email, DNI, organization).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("profiles").select("id, email, full_name, dni, organization_name").eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cgqhpsysmwcmaluscdeh";
var mcp_default = defineMcp({
  name: "accoro-mcp",
  title: "Accoro",
  version: "0.1.0",
  instructions: "Tools for Accoro, an event ticketing app. Use `list_public_events` to browse events open for ticket sales, `list_my_events` and `create_event` to manage events you organize, and `get_my_profile` to read the signed-in user's profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_public_events_default, list_my_events_default, create_event_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
